language: groovy
jdk:
  - oraclejdk8
sudo: false
branches:
  only:
  - grails3
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish --stacktrace --info '
env:
  global:
  - secure: hPmG2SGmylGFsb/C5sBxJlAFt/GFLa1Ncg/PU7q8oBvVwu3GXkH4QRO4a6Jl7yTsNw/hEG4UZp/WFd+BfzCmo3oKvUWSIvQrweAKzNEiiVKArOw3LFJ8+CMiPhkfhMg3CXurDm/fzUkl5getSz00Me2WdPk3obG+nKY39rGpoBQ=
  - secure: Gjro7XSNjemHc8WokUkiraQ729iLfzjBYTuT00Y+aa6zN+XeQHOj59WBOItap5w+Kp34FHEBNExc6jAizlyIWG/qM/g6GROyGFkzMO9QNUsBvEFpfhQKvdQwOndvxarQrEI5MiRJrT7dm3gFqjq5mswcCW6sRc2FTQLci/0Bl6g=
